"""Inspect AI Task Builder & Docker Sandbox Bridge.

Builds Inspect AI compatible evaluation tasks, dataset samples, and container isolation configurations
for code/shell agents per ADR-001 & ADR-005.
"""

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from agenteval.planning.models import CandidateTest


class DockerSandboxSpec(BaseModel):
    """Container sandbox configuration for Inspect AI execution."""

    model_config = ConfigDict(extra="forbid")

    image: str = Field(default="python:3.11-slim", description="Docker base image")
    memory_limit: str = Field(default="2g", description="Memory ceiling")
    cpu_limit: float = Field(default=1.0, ge=0.1, description="CPU ceiling")
    environment: dict[str, str] = Field(default_factory=dict, description="Injected env vars")
    workdir: str = Field(default="/workspace", description="Working directory inside container")


class InspectSample(BaseModel):
    """Single evaluation sample conforming to Inspect AI dataset format."""

    model_config = ConfigDict(extra="forbid")

    id: str
    input: str
    target: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class InspectTaskDefinition(BaseModel):
    """Specification of an Inspect AI evaluation task."""

    model_config = ConfigDict(extra="forbid")

    task_id: str
    name: str
    description: str
    sandbox: DockerSandboxSpec
    samples: list[InspectSample] = Field(default_factory=list)
    scoring_metrics: list[str] = Field(default_factory=list)


class InspectTaskBuilder:
    """Constructs Inspect AI evaluation tasks and datasets from candidate tests."""

    @staticmethod
    def is_docker_available() -> bool:
        """Return True if docker CLI is found and docker daemon responds."""
        docker_bin = shutil.which("docker")
        if not docker_bin:
            return False
        try:
            res = subprocess.run(
                [docker_bin, "info"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=2,
                check=False,
            )
            return res.returncode == 0
        except Exception:
            return False

    def build_task(
        self,
        agent_id: str,
        candidates: list[CandidateTest],
        sandbox_spec: DockerSandboxSpec | None = None,
    ) -> InspectTaskDefinition:
        """Convert CandidateTest suite into Inspect AI Task definition with container sandbox."""
        spec = sandbox_spec or DockerSandboxSpec()
        samples: list[InspectSample] = []

        for c in candidates:
            samples.append(
                InspectSample(
                    id=c.id,
                    input=c.user_prompt,
                    target=c.expected_behavior,
                    metadata={
                        "capability_id": c.capability_id,
                        "persona_id": c.persona_id,
                        "priority_tier": c.priority_tier.value if c.priority_tier else "P1",
                        "category": c.category,
                        "failure_mode": c.failure_mode,
                        "coverage_tags": c.coverage_tags,
                    },
                )
            )

        return InspectTaskDefinition(
            task_id=f"inspect-{agent_id}",
            name=f"AgentEval Inspect Task: {agent_id}",
            description=f"Isolated container evaluation task for agent '{agent_id}' ({len(candidates)} samples).",
            sandbox=spec,
            samples=samples,
            scoring_metrics=["exact_match", "model_graded_fact"],
        )

    def export_dataset_jsonl(
        self,
        task: InspectTaskDefinition,
        output_path: Path,
    ) -> Path:
        """Write task samples to a JSONL dataset file compatible with Inspect AI."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        lines = [json.dumps(s.model_dump()) for s in task.samples]
        output_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        return output_path

    def export_task_python_module(self, task: InspectTaskDefinition) -> str:
        """Generate standalone runnable Python module code using Inspect AI primitives."""
        samples_json = json.dumps([s.model_dump() for s in task.samples], indent=2)
        code = f'''"""Autogenerated Inspect AI Task module for {task.name}."""

import json
from inspect_ai import Task, task
from inspect_ai.dataset import MemoryDataset, Sample
from inspect_ai.scorer import includes
from inspect_ai.solver import generate

SAMPLES_DATA = {samples_json}

@task
def {task.task_id.replace("-", "_")}() -> Task:
    """Run sandboxed assurance evaluation."""
    samples = [
        Sample(
            id=s["id"],
            input=s["input"],
            target=s["target"],
            metadata=s.get("metadata", {{}}),
        )
        for s in SAMPLES_DATA
    ]
    return Task(
        dataset=MemoryDataset(samples),
        solver=[generate()],
        scorer=includes(),
        sandbox=("{task.sandbox.image}"),
    )
'''
        return code
